spring:
  profiles:
    active: test-sharding-double_write
  jpa: #jpa配置
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: goods-service