version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      ## 对外暴露的端口号
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    volumes:
      ## 挂载位置（kafka镜像和宿主机器之间时间保持一直）
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock  # 允许容器与容器与Docker守护进程通信 ，也就是使用docker 命令 ， 比如 容器中需要实例化其他Docker容器
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    ports:
      - "9092:9092"
    environment:
      ## 宿主机IP
      KAFKA_ADVERTISED_HOST_NAME: 182.92.217.111
      ## zk地址
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DELETE_RETENTION_MS: 1000
  kafka-manager:
    image: sheepkiller/kafka-manager
    environment:
      ## 宿主机IP
      ZK_HOSTS: 182.92.217.111
    ports:
      ## 暴露端口
      - "9001:9000"